<?php include 'blocks/header.php'; ?>
<?php include 'blocks/nav-bar-inverse.php'; ?>
<?php include 'blocks/alerts.php'; ?>
<?php include 'blocks/badges.php'; ?>
<?php include 'blocks/form-inputs.php'; ?>
<?php include 'blocks/form.php'; ?>
<?php include 'blocks/jumbotron.php'; ?>
<?php include 'blocks/labels.php'; ?>
<?php include 'blocks/list-badge.php'; ?>
<?php include 'blocks/list-heading.php'; ?>
<?php include 'blocks/nav-bar-indent.php'; ?>
<?php include 'blocks/nav-bar-inverse.php'; ?>
<?php include 'blocks/nav-breadcrums.php'; ?>
<?php include 'blocks/nav-pager.php'; ?>
<?php include 'blocks/nav-pager-wide.php'; ?>
<?php include 'blocks/nav-pagination.php'; ?>
<?php include 'blocks/nav-pills-horizontal.php'; ?>
<?php include 'blocks/nav-pills-vertical.php'; ?>
<?php include 'blocks/nav-tabs.php'; ?>
<?php include 'blocks/panels-alert.php'; ?>
<?php include 'blocks/panels-normal.php'; ?>
<?php include 'blocks/progress-bars.php'; ?>
<?php include 'blocks/table-responsive-style.php'; ?>
<?php include 'blocks/wells.php'; ?>
<?php include 'blocks/footer.php'; ?>
